name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # or your actual build command

      - name: Copy CNAME to out
        run: cp CNAME ./out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out